-- 20240221135716 - add migration

CREATE TABLE IF NOT EXISTS users (
   "id" UUID PRIMARY KEY,
   "name" TEXT NOT NULL,
   "last_name" TEXT NOT NULL,
   "email" TEXT NOT NULL UNIQUE,
   "password" TEXT NOT NULL,
   "company_id" UUID NOT NULL,

   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);